[[stack]]
name = "project_zomboid"
tags = ["gs2", "games"]
[stack.config]
server = "gameserver2"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/pzserver"
post_deploy.command = """
docker cp pzserver.ini pzserver:/data/.Zomboid/Server/
docker exec pzserver chown 1000:1000 /data/.Zomboid/Server/pzserver.ini
docker cp common.cfg pzserver:/data/config-lgsm/pzserver/
docker exec pzserver chown 1000:1000 /data/config-lgsm/pzserver/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=vh
####container name
CT_NAME=vhserver
####gamedig game type
GD_TYPE_ID=valheim
####server game port
GAME_PORT=2456
####server query port
GAME_QUERY=2456
####server ip
GAME_IP=10.42.0.90
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""