[[stack]]
name = "project_zomboid"
tags = ["ice", "games"]
[stack.config]
server = "darkmatter"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/pzserver"
config_files = [
  { path = "common.cfg", requires = "None" }
  { path = "pzserver.ini", requires = "None" }
]
post_deploy.command = """
docker cp pzserver.ini pzserver:/data/.Zomboid/Server/
docker exec pzserver chown 1000:1000 /data/.Zomboid/Server/pzserver.ini
docker cp common.cfg pzserver:/data/config-lgsm/pzserver/
docker exec pzserver chown 1000:1000 /data/config-lgsm/pzserver/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=pz
####container name
CT_NAME=pzserver
####gamedig game type
GD_TYPE_ID=projectzomboid
####server game port
GAME_PORT=16261
####server query port
GAME_QUERY=16262
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""