[[stack]]
name = "return_to_castle_wolfenstein"
tags = ["ice", "games"]
[stack.config]
server = "darkmatter"
linked_repo = "game_servers"
webhook_enabled = false
run_directory = "games/rtcwserver"
config_files = [
  { path = "common.cfg", requires = "None" },
  { path = "rtcwserver.cfg", requires = "None" }
]
post_deploy.command = """
docker cp rtcwserver.cfg rtcwserver:/data/serverfiles/main/
docker exec rtcwserver chown 1000:1000 /data/serverfiles/main/rtcwserver.cfg
docker cp common.cfg rtcwserver:/data/config-lgsm/rtcwserver/
docker exec rtcwserver chown 1000:1000 /data/config-lgsm/rtcwserver/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=rtcw
####container name
CT_NAME=rtcwserver
####gamedig game type
GD_TYPE_ID=rtcw
####server game port
GAME_PORT=27960
####server query port
GAME_QUERY=27960
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""