[[stack]]
name = "return_to_castle_wolfenstein"
tags = ["gs2", "games"]
[stack.config]
server = "gameserver2"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/rtcwserver"
post_deploy.command = """
docker cp rtcwserver.cfg rtcwserver:/data/serverfiles/main/
docker exec rtcwserver chown 1000:1000 /data/serverfiles/main/rtcwserver.cfg
docker cp common.cfg rtcwserver:/data/config-lgsm/rtcwserver/
docker exec rtcwserver chown 1000:1000 /data/config-lgsm/rtcwserver/common.cfg
"""