services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: serverlist
    networks:
      - icenet
    #ports:
    #  - 3000:3000
    restart: unless-stopped
    volumes:
      - config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker.yaml:/app/config/docker.yaml
      - ./settings.yaml:/app/config/settings.yaml
      - ./widgets.yaml:/app/config/widgets.yaml
      - ./custom.css:/app/config/custom.css
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=10.42.0.3:3000,icicleskill.win
    labels:
      # Proxy Resource Configuration
      - pangolin.proxy-resources.servers.name=servers
      - pangolin.proxy-resources.servers.full-domain=icicleskill.win
      - pangolin.proxy-resources.servers.protocol=http
      - pangolin.proxy-resources.servers.targets[0].method=http
      - pangolin.proxy-resources.servers.targets[0].hostname=serverlist
      - pangolin.proxy-resources.servers.targets[0].port=3000
volumes:
  config:
networks:
  icenet:
    driver: bridge
    name: icenet