[[stack]]
name = "counter_strike_16"
tags = ["ice", "games"]
[stack.config]
server = "darkmatter"
linked_repo = "game_servers"
webhook_enabled = false
run_directory = "games/csserver"
config_files = [
  { path = "common.cfg", requires = "None" },
  { path = "csserver.cfg", requires = "None" }
]
post_deploy.command = """
docker cp csserver.cfg csserver:/data/serverfiles/cstrike/
docker exec csserver chown 1000:1000 /data/serverfiles/cstrike/csserver.cfg
docker cp common.cfg csserver:/data/config-lgsm/csserver/
docker exec csserver chown 1000:1000 /data/config-lgsm/csserver/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=cs
####container name
CT_NAME=csserver
####gamedig game type
GD_TYPE_ID=counterstrike16
####server game port
GAME_PORT=27015
####server query port
GAME_QUERY=27015
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""