[[stack]]
name = "left_4_dead_2"
tags = ["ice", "games"]
[stack.config]
server = "darkmatter"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/l4d2server"
config_files = [
  { path = "common.cfg", requires = "None" },
  { path = "l4d2server.cfg", requires = "None" }
]
post_deploy.command = """
docker cp l4d2server.cfg l4d2server:/data/serverfiles/left4dead2/cfg/
docker exec l4d2server chown 1000:1000 /data/serverfiles/left4dead2/cfg/l4d2server.cfg
docker cp common.cfg l4d2server:/data/config-lgsm/l4d2server/
docker exec l4d2server chown 1000:1000 /data/config-lgsm/l4d2server/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=l4d2
####container name
CT_NAME=l4d2server
####gamedig game type
GD_TYPE_ID=l4d2
####server game port
GAME_PORT=27015
####server query port
GAME_QUERY=27015
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""