[[stack]]
name = "arma_reforger"
tags = ["ice", "games"]
[stack.config]
server = "darkmatter"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/armarserver"
config_files = [
  { path = "common.cfg", requires = "None" },
  { path = "armarserver_config.json", requires = "None" }
]
post_deploy.command = """
docker cp armarserver_config.json armarserver:/data/serverfiles/
docker exec armarserver chown 1000:1000 /data/serverfiles/armarserver_config.json
docker cp common.cfg armarserver:/data/config-lgsm/armarserver/
docker exec armarserver chown 1000:1000 /data/config-lgsm/armarserver/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=armar
####container name
CT_NAME=armarserver
####gamedig game type
GD_TYPE_ID=armar
####server game port
GAME_PORT=2001
####server query port
GAME_QUERY=17777
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""