services:
  newt:
    image: fosrl/newt
    container_name: newt
    networks:
      - icenet
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT=https://darvaza.ckrl.cloud
      - NEWT_ID=y6isp821nze17va
      - NEWT_SECRET=kitr6cuskrza4jyi2tbjcru7slm45sdzro7uhi566jf34ps0
networks:
  icenet:
    driver: bridge
    name: icenet