[[stack]]
name = "newt-ice-darkmatter"
tags = ["ice", "apps"]
[stack.config]
server = "darkmatter"
linked_repo = "game_servers"
webhook_enabled = false
run_directory = "apps/newt-ice-darkmatter"