[[stack]]
name = "day_z"
tags = ["ice", "games"]
[stack.config]
server = "darkmatter"
linked_repo = "game_servers"
webhook_enabled = false
run_directory = "games/dayzserver"
config_files = [
  { path = "common.cfg", requires = "None" },
  { path = "dayzserver.cfg", requires = "None" }
]
post_deploy.command = """
docker cp dayzserver.server.cfg dayzserver:/data/serverfiles/cfg/
docker exec dayzserver chown 1000:1000 /data/serverfiles/cfg/dayzserver.server.cfg
docker cp common.cfg dayzserver:/data/config-lgsm/dayzserver/
docker exec dayzserver chown 1000:1000 /data/config-lgsm/dayzserver/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=dayz
####container name
CT_NAME=dayzserver
####gamedig game type
GD_TYPE_ID=dayz
####server game port
GAME_PORT=2302
####server query port
GAME_QUERY=2302
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""