[[stack]]
name = "moh_allied_assault"
tags = ["ice", "games"]
[stack.config]
server = "darkmatter"
linked_repo = "game_servers"
webhook_enabled = false
run_directory = "games/mohaaserver"
config_files = [
  { path = "common.cfg", requires = "None" },
  { path = "Game.ini", requires = "None" }
]
post_deploy.command = """
docker cp mohaaserver.cfg mohaaserver:/data/serverfiles/main
docker exec mohaaserver chown 1000:1000 /data/serverfiles/main/mohaaserver.cfg
docker cp common.cfg mohaaserver:/data/config-lgsm/mohaaserver/
docker exec mohaaserver chown 1000:1000 /data/config-lgsm/mohaaserver/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=mohaa
####container name
CT_NAME=mohaaserver
####gamedig game type
GD_TYPE_ID=mohaa
####server game port
GAME_PORT=12203
####server query port
GAME_QUERY=12203
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""