[[stack]]
name = "garrys_mod"
tags = ["ice", "games"]
[stack.config]
server = "darkmatter"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/gmodserver"
config_files = [
  { path = "common.cfg", requires = "None" }
  { path = "gmodserver.cfg", requires = "None" }
]
post_deploy.command = """
docker cp gmodserver.cfg gmodserver:/data/serverfiles/garrysmod/cfg/
docker exec gmodserver chown 1000:1000 /data/serverfiles/garrysmod/cfg/gmodserver.cfg
docker cp common.cfg gmodserver:/data/config-lgsm/gmodserver/
docker exec gmodserver chown 1000:1000 /data/config-lgsm/gmodserver/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=gmod
####container name
CT_NAME=gmodserver
####gamedig game type
GD_TYPE_ID=garrysmod
####server game port
GAME_PORT=27015
####server query port
GAME_QUERY=27015
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""