[[stack]]
name = "garrys_mod"
tags = ["gs1", "games"]
[stack.config]
server = "gameserver1"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/gmodserver"
post_deploy.command = """
docker cp gmodserver.cfg gmodserver:/data/serverfiles/garrysmod/cfg/
docker exec gmodserver chown 1000:1000 /data/serverfiles/garrysmod/cfg/gmodserver.cfg
docker cp common.cfg gmodserver:/data/config-lgsm/gmodserver/
docker exec gmodserver chown 1000:1000 /data/config-lgsm/gmodserver/common.cfg
"""