services:
  fireshare:
    container_name: fireshare
    image: shaneisrael/fireshare:latest
    networks:
      - llamanet
    #ports:
    #  - "8080:80"
    volumes:
      - data:/data
      - processed:/processed
      - videos:/videos
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=dontpetthellama
      - SECRET_KEY=llamasarecool!
      - MINUTES_BETWEEN_VIDEO_SCANS=5
      # The location in the video thumbnails are generated. A value between 0-100 where 50 would be the frame in the middle of the video file and 0 would be the first frame of the video.
      - THUMBNAIL_VIDEO_LOCATION=15
      # The domain your instance is hosted at. (do not add http or https) e.x: v.fireshare.net, this is required for opengraph to work correctly for shared links. DO NOT SURROUND IN QUOTES.
      - DOMAIN=clips.at.lanallnight.com
      - PUID=1000
      - PGID=1000
    labels:
      # Proxy Resource Configuration
      - pangolin.proxy-resources.clips.name=clips
      - pangolin.proxy-resources.clips.full-domain=clips.at.lanallnight.com
      - pangolin.proxy-resources.clips.protocol=http
      - pangolin.proxy-resources.clips.targets[0].method=http
      - pangolin.proxy-resources.clips.targets[0].hostname=fireshare
      - pangolin.proxy-resources.clips.targets[0].port=80
volumes:
  data:
  processed:
  videos:
networks:
  llamanet:
    driver: bridge
    name: llamanet