services:
  t5mp-1:
    image: ghcr.io/ayymoss/plutainer:latest
    container_name: t5mp-1
    hostname: t5mp-1
    restart: unless-stopped
    networks:
      - icenet
    ports:
      - "28962:28962/udp"
    volumes:
      - /opt/GameFiles/T5ServerFiles:/home/plutainer/gamefiles:ro
      - ./t5mp-1:/home/plutainer/app
    environment:
      - PLUTO_PORT=28962
      - PLUTO_SERVER_KEY=${T5MP_PLUTO_SERVER_KEY}
      - PLUTO_CONFIG_FILE=dedicated.cfg
      - PLUTO_GAME=t5mp
      - PLUTO_MAX_CLIENTS=18
  
  t5sp-1:
    image: ghcr.io/ayymoss/plutainer:latest
    container_name: t5sp-1
    hostname: t5sp-1
    restart: unless-stopped
    networks:
      - icenet
    ports:
      - "28963:28963/udp"
    volumes:
      - /opt/GameFiles/T5ServerFiles:/home/plutainer/gamefiles:ro
      - ./t5sp-1:/home/plutainer/app
    environment:
      - PLUTO_PORT=28963
      - PLUTO_SERVER_KEY=${T5SP_PLUTO_SERVER_KEY}
      - PLUTO_CONFIG_FILE=dedicated_sp.cfg
      - PLUTO_GAME=t5sp
      - PLUTO_MOD=mods/Stairway_to_hell_bo1
      - PLUTO_MAX_CLIENTS=4
networks:
  icenet:
    driver: bridge
    name: icenet