services:
  iw4xmp-1:
    image: ghcr.io/ayymoss/plutainer:latest
    container_name: iw4xmp-1
    restart: unless-stopped
    networks:
      - icenet
    ports:
      - "28970:28970/udp"
      #- "28970:28970/tcp" # TCP is needed for modlist metadata (not required if not hosting mods)
    volumes:
      - /opt/GameFiles/IW4xServerFiles:/home/plutainer/gamefiles
      - ./iw4xmp-1:/home/plutainer/app
    environment:
      - IW4X_PORT=28970
      - IW4X_CONFIG_FILE=server.cfg
      - IW4X_GAME=iw4x
      - IW4X_AUTO_UPDATE=false

  t6zm-1:
    image: ghcr.io/ayymoss/plutainer:latest
    container_name: t6zm-1
    hostname: t6zm-1
    restart: unless-stopped
    networks:
      - icenet
    ports:
      - "4976:4976/udp"
    volumes:
      - /opt/GameFiles/T6ServerFiles:/home/plutainer/gamefiles:ro
      - ./t6zm-1:/home/plutainer/app
    environment:
      - PLUTO_PORT=4976
      - PLUTO_SERVER_KEY=${T6ZM_PLUTO_SERVER_KEY}
      - PLUTO_CONFIG_FILE=dedicated_zm.cfg
      - PLUTO_GAME=t6zm

  t6mp-1:
    image: ghcr.io/ayymoss/plutainer:latest
    container_name: t6mp-1
    hostname: t6mp-1
    restart: unless-stopped
    networks:
      - icenet
    ports:
      - "4977:4977/udp"
    volumes:
      - /opt/GameFiles/T6ServerFiles:/home/plutainer/gamefiles:ro
      - ./t6mp-1:/home/plutainer/app
    environment:
      - PLUTO_PORT=4977
      - PLUTO_SERVER_KEY=${T6MP_PLUTO_SERVER_KEY}
      - PLUTO_CONFIG_FILE=dedicated.cfg
      - PLUTO_GAME=t6mp
  
  t4sp-1:
    image: ghcr.io/ayymoss/plutainer:latest
    container_name: t4sp-1
    hostname: t4sp-1
    restart: unless-stopped
    networks:
      - icenet
    ports:
      - "28960:28960/udp"
    volumes:
      - /opt/GameFiles/T4ServerFiles:/home/plutainer/gamefiles:ro
      - ./t4sp-1:/home/plutainer/app
    environment:
      - PLUTO_PORT=28960
      - PLUTO_SERVER_KEY=${T4SP_PLUTO_SERVER_KEY}
      - PLUTO_CONFIG_FILE=server_zm.cfg
      - PLUTO_GAME=t4sp
  
  t4mp-1:
    image: ghcr.io/ayymoss/plutainer:latest
    container_name: t4mp-1
    hostname: t4mp-1
    restart: unless-stopped
    networks:
      - icenet
    ports:
      - "28961:28961/udp"
    volumes:
      - /opt/GameFiles/T4ServerFiles:/home/plutainer/gamefiles:ro
      - ./t4mp-1:/home/plutainer/app
    environment:
      - PLUTO_PORT=28961
      - PLUTO_SERVER_KEY=${T4MP_PLUTO_SERVER_KEY}
      - PLUTO_CONFIG_FILE=server.cfg
      - PLUTO_GAME=t4mp
  
  t5mp-1:
    image: ghcr.io/ayymoss/plutainer:latest
    container_name: t5mp-1
    hostname: t5mp-1
    restart: unless-stopped
    networks:
      - icenet
    ports:
      - "28962:28962/udp"
    volumes:
      - /opt/GameFiles/T5ServerFiles:/home/plutainer/gamefiles:ro
      - ./t5mp-1:/home/plutainer/app
    environment:
      - PLUTO_PORT=28962
      - PLUTO_SERVER_KEY=${T5MP_PLUTO_SERVER_KEY}
      - PLUTO_CONFIG_FILE=dedicated.cfg
      - PLUTO_GAME=t5mp
      - PLUTO_MAX_CLIENTS=18
  
  t5sp-1:
    image: ghcr.io/ayymoss/plutainer:latest
    container_name: t5sp-1
    hostname: t5sp-1
    restart: unless-stopped
    networks:
      - icenet
    ports:
      - "28963:28963/udp"
    volumes:
      - /opt/GameFiles/T5ServerFiles:/home/plutainer/gamefiles:ro
      - ./t5sp-1:/home/plutainer/app
    environment:
      - PLUTO_PORT=28963
      - PLUTO_SERVER_KEY=${T5SP_PLUTO_SERVER_KEY}
      - PLUTO_CONFIG_FILE=dedicated_sp.cfg
      - PLUTO_GAME=t5sp
      - PLUTO_MOD=mods/Stairway_to_hell_bo1
      - PLUTO_MAX_CLIENTS=4
  
  iw4madmin:
    image: ghcr.io/raidmax/iw4madmin:latest
    container_name: iw4madmin
    restart: unless-stopped
    networks:
      - icenet
    ports:
      - "1624:1624"
      #- You need to expose any IW4X_NET_LOG_IP ports.
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./IW4MAdmin/Configuration:/app/Configuration
      - ./IW4MAdmin/Plugins:/app/Plugins
      - ./IW4MAdmin/Localization:/app/Localization
      - ./IW4MAdmin/Database:/app/Database
      - ./IW4MAdmin/Log:/app/Log
      - ./iw4xmp-1/gamefiles/userraw/logs/games_mp.log:/app/gamelogs/iw4xmp-1/gamefiles/userraw/logs/games_mp.log:ro
      - ./t4mp-1/plutonium/storage/t4/main/games_mp.log:/app/gamelogs/t4mp-1/plutonium/storage/t4/main/games_mp.log:ro
      - ./t4sp-1/plutonium/storage/t4/main/games_zm.log:/app/gamelogs/t4sp-1/plutonium/storage/t4/main/games_zm.log:ro
      - ./t5mp-1/plutonium/storage/t5/main/logs/games_mp.log:/app/gamelogs/t5mp-1/plutonium/storage/t5/main/logs/games_mp.log:ro
      - ./t5sp-1/plutonium/storage/t5/mods/Stairway_to_hell_bo1/logs/games_zm.log:/app/gamelogs/t5sp-1/plutonium/storage/t5/mods/Stairway_to_hell_bo1/logs/games_zm.log:ro
      - ./t6mp-1/plutonium/storage/t6/main/logs/games_mp.log:/app/gamelogs/t6mp-1/plutonium/storage/t6/main/logs/games_mp.log:ro
      - ./t6zm-1/plutonium/storage/t6/main/logs/games_zm.log:/app/gamelogs/t6zm-1/plutonium/storage/t6/main/logs/games_zm.log:ro
    depends_on:
      iw4xmp-1:
        condition: service_healthy
      t6zm-1:
        condition: service_healthy
      t6mp-1:
        condition: service_healthy
      t4sp-1:
        condition: service_healthy
      t4mp-1:
        condition: service_healthy
      t5mp-1:
        condition: service_healthy
      t5sp-1:
        condition: service_healthy

networks:
  icenet:
    driver: bridge
    name: icenet