[[stack]]
name = "mordhau"
tags = ["ice", "games"]
[stack.config]
server = "darkmatter"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/mhserver"
config_files = [
  { path = "common.cfg", requires = "None" },
  { path = "mhserver.cfg", requires = "None" }
]
post_deploy.command = """
docker cp Game.ini mhserver:/data/serverfiles/Mordhau/Saved/Config/Linuxserver/
docker exec mhserver chown 1000:1000 /data/serverfiles/Mordhau/Saved/Config/Linuxserver/Game.ini
docker cp common.cfg mhserver:/data/config-lgsm/mhserver/
docker exec mhserver chown 1000:1000 /data/config-lgsm/mhserver/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=mh
####container name
CT_NAME=mhserver
####gamedig game type
GD_TYPE_ID=mordhau
####server game port
GAME_PORT=7777
####server query port
GAME_QUERY=27015
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""