services:
  teamspeak:
    image: teamspeak
    container_name: ts3
    hostname: ts3
    restart: always
    #ports:
    #  - 9987:9987/udp
    #  - 10011:10011
    #  - 30033:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: mNncD6UpgzXsd752
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    labels:
      - homepage.group=Services
      - homepage.name=Teamspeak 3
      - homepage.icon=steam.png
      - homepage.widget.type=gamedig
      - homepage.widget.serverType=teamspeak3
      - homepage.widget.url=udp://192.168.50.52:10011
      - homepage.widget.fields=["status", "map", "currentPlayers", "ping"]
      - homepage.container=ts3
      - homepage.showStats=false
      # Proxy Resource Configuration
      - pangolin.proxy-resources.ts3-9987.name=ts3-9987
      - pangolin.proxy-resources.ts3-9987.protocol=udp
      - pangolin.proxy-resources.ts3-9987.proxy-port=9987
      - pangolin.proxy-resources.ts3-9987.targets[0].hostname=ts3
      - pangolin.proxy-resources.ts3-9987.targets[0].port=9987
      - pangolin.proxy-resources.ts3-10011.name=ts3-10011
      - pangolin.proxy-resources.ts3-10011.protocol=tcp
      - pangolin.proxy-resources.ts3-10011.proxy-port=10011
      - pangolin.proxy-resources.ts3-10011.targets[0].hostname=ts3
      - pangolin.proxy-resources.ts3-10011.targets[0].port=10011
      - pangolin.proxy-resources.ts3-30033.name=ts3-30033
      - pangolin.proxy-resources.ts3-30033.protocol=tcp
      - pangolin.proxy-resources.ts3-30033.proxy-port=30033
      - pangolin.proxy-resources.ts3-30033.targets[0].hostname=ts3
      - pangolin.proxy-resources.ts3-30033.targets[0].port=30033
    volumes:
      - ./ts3server.ini:/data/ts3server.ini:ro
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mNncD6UpgzXsd752
      MYSQL_DATABASE: teamspeak