[[stack]]
name = "unreal_tournament_2004"
tags = ["ice", "games"]
[stack.config]
server = "darkmatter"
linked_repo = "game_servers"
webhook_enabled = false
run_directory = "games/ut2k4server"
config_files = [
  { path = "common.cfg", requires = "None" },
  { path = "ut2k4server.ini", requires = "None" }
]
post_deploy.command = """
docker cp ut2k4server.ini ut2k4server:/data/serverfiles/System/
docker exec ut2k4server chown 1000:1000 /data/serverfiles/System/ut2k4server.ini
docker cp common.cfg ut2k4server:/data/config-lgsm/ut2k4server/
docker exec ut2k4server chown 1000:1000 /data/config-lgsm/ut2k4server/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=ut2k4
####container name
CT_NAME=ut2k4server
####gamedig game type
GD_TYPE_ID=unrealtournament2004
####server game port
GAME_PORT=7777
####server query port
GAME_QUERY=7778
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""