app:
  dashboard_url: "https://pangolin.at.lanallnight.com"
  log_level: "info"
  save_logs: false

domains:
  domain1:
    base_domain: "at.lanallnight.com"
    cert_resolver: "letsencrypt"

server:
  external_port: 3000
  internal_port: 3001
  next_port: 3002
  secret: "d29@a2b.2HFTe3bMtZHGneNYgQFKT3X5vm8HuXUXBcq7aVyNZjdGt7Dx-_A@9b9y"

traefik:
  cert_resolver: "letsencrypt"
  http_entrypoint: "web"
  https_entrypoint: "websecure"

gerbil:
  start_port: 51820
  base_endpoint: "pangolin.at.lanallnight.com"

flags:
  require_email_verification: true
  disable_signup_without_invite: true
  disable_user_create_org: true
  allow_raw_resources: true
  allow_base_domain_resources: true