services:
  dns:
    container_name: dns
    hostname: dns
    image: technitium/dns-server:latest
    networks:
      llamamac:
        ipv4_address: 192.168.50.20
    environment:
      - DNS_SERVER_DOMAIN=dns.at.lanallnight.com
    volumes:
      - config:/etc/dns
    restart: unless-stopped
volumes:
    config:
networks:
  llamamac:
    name: llamamac
    driver: macvlan
    driver_opts:
      parent: enp6s18
    ipam:
      config:
        - subnet: "192.168.50.0/23"
          gateway: "192.168.50.1"