[[stack]]
name = "unreal_tournament"
tags = ["gs2", "games"]
[stack.config]
server = "gameserver2"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/utserver"
post_deploy.command = """
docker cp Game.ini utserver:/data/serverfiles/LinuxServer/UnrealTournament/Saved/Config/LinuxServer/
docker exec utserver chown 1000:1000 /data/serverfiles/LinuxServer/UnrealTournament/Saved/Config/LinuxServer/Game.ini
docker cp common.cfg utserver:/data/config-lgsm/utserver/
docker exec utserver chown 1000:1000 /data/config-lgsm/utserver/common.cfg
"""