[[stack]]
name = "unreal_tournament_99"
tags = ["gs2", "games"]
[stack.config]
server = "gameserver2"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/ut99server"
post_deploy.command = """
docker cp ut99server.ini ut99server:/data/serverfiles/System64/
docker exec ut99server chown 1000:1000 /data/serverfiles/System64/ut99server.ini
docker cp common.cfg ut99server:/data/config-lgsm/ut99server/
docker exec ut99server chown 1000:1000 /data/config-lgsm/ut99server/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=vh
####container name
CT_NAME=vhserver
####gamedig game type
GD_TYPE_ID=valheim
####server game port
GAME_PORT=2456
####server query port
GAME_QUERY=2456
####server ip
GAME_IP=10.42.0.90
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""