[[stack]]
name = "minecraft_java"
tags = ["ice", "games"]
[stack.config]
server = "darkmatter"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/mcserver"
config_files = [
  { path = "common.cfg", requires = "None" },
  { path = "server.properties", requires = "None" }
]
post_deploy.command = """
docker cp server.properties mcserver:/data/serverfiles/
docker exec mcserver chown 1000:1000 /data/serverfiles/server.properties
docker cp common.cfg mcserver:/data/config-lgsm/mcserver/
docker exec mcserver chown 1000:1000 /data/config-lgsm/mcserver/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=mc
####container name
CT_NAME=mcserver
####gamedig game type
GD_TYPE_ID=minecraft
####server game port
GAME_PORT=25565
####server query port
GAME_QUERY=25565
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""