[[stack]]
name = "minecraft_java"
tags = ["gs1", "games"]
[stack.config]
server = "gameserver1"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/mcserver"
post_deploy.command = """
docker cp server.properties mcserver:/data/serverfiles/
docker exec mcserver chown 1000:1000 /data/serverfiles/server.properties
docker cp common.cfg mcserver:/data/config-lgsm/mcserver/
docker exec mcserver chown 1000:1000 /data/config-lgsm/mcserver/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=vh
####container name
CT_NAME=vhserver
####gamedig game type
GD_TYPE_ID=valheim
####server game port
GAME_PORT=2456
####server query port
GAME_QUERY=2456
####server ip
GAME_IP=10.42.0.90
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""