[[stack]]
name = "7_days_to_die"
tags = ["ice", "games"]
[stack.config]
server = "darkamtter"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/sdtdserver"
config_files = [
  { path = "common.cfg", requires = "None" }
  { path = "Game.ini", requires = "None" }
]
post_deploy.command = """
docker cp sdtdserver.xml sdtdserver:/data/serverfiles/
docker exec sdtdserver chown 1000:1000 /data/serverfiles/sdtdserver.xml
docker cp common.cfg sdtdserver:/data/config-lgsm/sdtdserver/
docker exec sdtdserver chown 1000:1000 /data/config-lgsm/sdtdserver/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=sdtd
####container name
CT_NAME=sdtdserver
####gamedig game type
GD_TYPE_ID=sdtd
####server game port
GAME_PORT=26900
####server query port
GAME_QUERY=26900
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""