[[stack]]
name = "team_fortress_2"
tags = ["gs2", "games"]
[stack.config]
server = "gameserver2"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/tf2server"
post_deploy.command = """
docker cp tf2server.cfg tf2server:/data/serverfiles/tf/cfg/
docker exec tf2server chown 1000:1000 /data/serverfiles/tf/cfg/tf2server.cfg
docker cp common.cfg tf2server:/data/config-lgsm/tf2server/
docker exec tf2server chown 1000:1000 /data/config-lgsm/tf2server/common.cfg
"""