[[stack]]
name = "team_fortress_2"
tags = ["ice", "games"]
[stack.config]
server = "darkmatter"
linked_repo = "game_servers"
webhook_enabled = false
run_directory = "games/tf2server"
config_files = [
  { path = "common.cfg", requires = "None" },
  { path = "tf2server.cfg", requires = "None" }
]
post_deploy.command = """
docker cp tf2server.cfg tf2server:/data/serverfiles/tf/cfg/
docker exec tf2server chown 1000:1000 /data/serverfiles/tf/cfg/tf2server.cfg
docker cp common.cfg tf2server:/data/config-lgsm/tf2server/
docker exec tf2server chown 1000:1000 /data/config-lgsm/tf2server/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=tf2
####container name
CT_NAME=tf2server
####gamedig game type
GD_TYPE_ID=teamfortress2
####server game port
GAME_PORT=27015
####server query port
GAME_QUERY=27015
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""