[[stack]]
name = "factorio"
tags = ["ice", "games"]
[stack.config]
server = "darkamtter"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/fctrserver"
config_files = [
  { path = "common.cfg", requires = "None" },
  { path = "Game.ini", requires = "None" }
]
post_deploy.command = """
docker cp fctrserver.json fctrserver:/data/serverfiles/bin/x64/data/
docker exec fctrserver chown 1000:1000 /data/serverfiles/bin/x64/data/fctrserver.json
docker cp common.cfg fctrserver:/data/config-lgsm/fctrserver/
docker exec fctrserver chown 1000:1000 /data/config-lgsm/fctrserver/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=fctr
####container name
CT_NAME=fctrserver
####gamedig game type
GD_TYPE_ID=factorio
####server game port
GAME_PORT=34197
####server query port
GAME_QUERY=34197
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""