title: LAN All Night 12 Servers
background: 
  image: https://lanallnight.com/wp-content/uploads/2025/06/LAN12-Main-Graphic-Wallpapers_Collage-Logo-4k-Large.jpg
  blur: xs
  opacity: 75
theme: dark
color: slate
headerStyle: clean
