[[stack]]
name = "arma_3"
tags = ["ice", "games"]
[stack.config]
server = "darkmatter"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/arma3server"
config_files = [
  { path = "common.cfg", requires = "None" }
  { path = "network.cfg", requires = "None" }
  { path = "server.cfg", requires = "None" }
]
post_deploy.command = """
docker cp server.cfg arma3server:/data/serverfiles/cfg/
docker exec arma3server chown 1000:1000 /data/serverfiles/cfg/server.cfg
docker cp network.cfg arma3server:/data/serverfiles/cfg/
docker exec arma3server chown 1000:1000 /data/serverfiles/cfg/network.cfg
docker cp common.cfg arma3server:/data/config-lgsm/arma3server/
docker exec arma3server chown 1000:1000 /data/config-lgsm/arma3server/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=arma3
####container name
CT_NAME=arma3server
####gamedig game type
GD_TYPE_ID=arma3
####server game port
GAME_PORT=2302
####server query port
GAME_QUERY=2302
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""