services:
  pangolin:
    image: fosrl/pangolin:latest
    container_name: pangolin
    restart: unless-stopped
    networks:
      - llamanet
    volumes:
      - config:/app/config
      - ./config/config.yml:/app/config/config.yml:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
      interval: "3s"
      timeout: "3s"
      retries: 15
  gerbil:
    image: fosrl/gerbil:latest
    container_name: gerbil
    restart: unless-stopped
    networks:
      - llamanet
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --reachableAt=http://gerbil:3003
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/gerbil/get-config
      - --reportBandwidthTo=http://pangolin:3001/api/v1/gerbil/receive-bandwidth
    volumes:
      - config:/var/config
      - ./config/config.yml:/var/config/config.yml:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
      - 443:443 # Port for traefik because of the network_mode
      - 80:80 # Port for traefik because of the network_mode
      ## teamspeak3/6
      - 9987:9987/udp #voice
      - 30033:30033/tcp #files
      - 10080:10080/tcp #webquery
      - 10011:10011/tcp #webquery
      ## restreamer
      - 1935:1935/tcp #rtmp
      - 1936:1936/tcp #rtmps
      - 6000:6000/udp #srt
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    network_mode: service:gerbil # Ports appear on the gerbil service
    depends_on:
      pangolin:
        condition: service_healthy
    env_file: .env
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    volumes:
      - ./config/traefik:/etc/traefik:ro # Volume to store the Traefik configuration
      - ./config/letsencrypt:/letsencrypt

networks:
  llamanet:
    driver: bridge
    name: llamanet
volumes:
  config:
