[[stack]]
name = "pangolin"
tags = ["mgmt", "services"]
[stack.config]
server = "mgmt"
linked_repo = "docker"
webhook_enabled = false
run_directory = "apps/pangolin"
environment = """
DREAMHOST_API_KEY = [[DREAMHOST_API_KEY]]
"""