[[stack]]
name = "battlefield_1942"
tags = ["gs1", "games"]
[stack.config]
server = "gameserver1"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/bf1942server"
post_deploy.command = """
docker cp serversettings.con bf1942server:/data/serverfiles/mods/bf1942/settings/
docker exec bf1942server chown 1000:1000 /data/serverfiles/mods/bf1942/settings/serversettings.con
docker cp common.cfg bf1942server:/data/config-lgsm/bf1942server/
docker exec bf1942server chown 1000:1000 /data/config-lgsm/bf1942server/common.cfg
"""