[[stack]]
name = "killing_floor"
tags = ["ice", "games"]
[stack.config]
server = "darkamtter"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/kfserver"
config_files = [
  { path = "common.cfg", requires = "None" }
  { path = "Game.ini", requires = "None" }
]
post_deploy.command = """
docker cp kfserver.ini kfserver:/data/serverfiles/System/
docker exec kfserver chown 1000:1000 /data/serverfiles/System/kfserver.ini
docker cp common.cfg kfserver:/data/config-lgsm/kfserver/
docker exec kfserver chown 1000:1000 /data/config-lgsm/kfserver/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=kf
####container name
CT_NAME=kfserver
####gamedig game type
GD_TYPE_ID=killingfloor
####server game port
GAME_PORT=7707
####server query port
GAME_QUERY=7708
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""