[[stack]]
name = "killing_floor_2"
tags = ["ice", "games"]
[stack.config]
server = "darkamtter"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/kf2server"
config_files = [
  { path = "common.cfg", requires = "None" },
  { path = "Game.ini", requires = "None" }
]
post_deploy.command = """
docker cp kf2server.ini kf2server:/data/serverfiles/System/
docker exec kf2server chown 1000:1000 /data/serverfiles/System/kf2server.ini
docker cp common.cfg kf2server:/data/config-lgsm/kf2server/
docker exec kf2server chown 1000:1000 /data/config-lgsm/kf2server/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=kf2
####container name
CT_NAME=kf2server
####gamedig game type
GD_TYPE_ID=killingfloor2
####server game port
GAME_PORT=7707
####server query port
GAME_QUERY=7708
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""