[[stack]]
name = "day_of_defeat_source"
tags = ["ice", "games"]
[stack.config]
server = "darkmatter"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/dodsserver"
config_files = [
  { path = "common.cfg", requires = "None" }
  { path = "dodsserver.cfg", requires = "None" }
]
post_deploy.command = """
docker cp dodsserver.cfg dodsserver:/data/serverfiles/dod/cfg/
docker exec dodsserver chown 1000:1000 /data/serverfiles/dod/cfg/dodsserver.cfg
docker cp common.cfg dodsserver:/data/config-lgsm/dodsserver/
docker exec dodsserver chown 1000:1000 /data/config-lgsm/dodsserver/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=dods
####container name
CT_NAME=dodsserver
####gamedig game type
GD_TYPE_ID=dods
####server game port
GAME_PORT=27015
####server query port
GAME_QUERY=27015
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""