[[stack]]
name = "black_mesa_deathmatch"
tags = ["ice", "games"]
[stack.config]
server = "darkmatter"
linked_repo = "game_servers"
webhook_enabled = false
run_directory = "games/bmdmserver"
config_files = [
  { path = "common.cfg", requires = "None" },
  { path = "bmdmserver.cfg", requires = "None" }
]
post_deploy.command = """
docker cp bmdmserver.cfg bmdmserver:/data/serverfiles/bms/cfg/
docker exec bmdmserver chown 1000:1000 /data/serverfiles/bms/cfg/bmdmserver.cfg
docker cp common.cfg bmdmserver:/data/config-lgsm/bmdmserver/
docker exec bmdmserver chown 1000:1000 /data/config-lgsm/bmdmserver/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=bmdm
####container name
CT_NAME=bmdmserver
####gamedig game type
GD_TYPE_ID=blackmesa
####server game port
GAME_PORT=27015
####server query port
GAME_QUERY=27015
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""