services:
  lgsm:
    image: gameservermanagers/gameserver:vh
    restart: unless-stopped
    networks:
      icemac:
        ipv4_address: 10.42.0.${VH_IP}
    volumes:
      - data:/data
    container_name: vhserver
    labels:
      - homepage.group=Games
      - homepage.name=Valhiem
      - homepage.icon=https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/refs/heads/master/lgsm/data/gameicons/vh-icon.png
      - homepage.href=steam://connect/192.168.50.${VH_IP}:${VH_PORT}
      - homepage.widget.type=gamedig
      - homepage.widget.serverType=valhiem
      - homepage.widget.url=udp://192.168.50.${VH_IP}:${VH_QUERY}
      - homepage.widget.fields=["status", "map", "currentPlayers", "ping"]
      - homepage.container=vhserver
      - homepage.showStats=false
volumes:
  data:
    name: vhserver_data
networks:
  icemac:
    name: icemac
    driver: macvlan
    driver_opts:
      parent: ${IF_NAME}
    ipam:
      config:
        - subnet: "10.42.0.0/24"
          gateway: "10.42.0.1"