[[stack]]
name = "valheim"
tags = ["ice", "games"]
[stack.config]
server = "darkmatter"
linked_repo = "game_servers"
webhook_enabled = false
run_directory = "games/vhserver"
config_files = [
  { path = "common.cfg", requires = "None" }
]
post_deploy.command = """
docker cp common.cfg vhserver:/data/config-lgsm/vhserver/
docker exec vhserver chown 1000:1000 /data/config-lgsm/vhserver/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=vh
####container name
CT_NAME=vhserver
####gamedig game type
GD_TYPE_ID=valheim
####server game port
GAME_PORT=2456
####server query port
GAME_QUERY=2456
####server ip
GAME_IP=10.42.0.90
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""