services:
  lgsm:
    image: gameservermanagers/gameserver:ut3
    restart: unless-stopped
    networks:
      llamamac:
        ipv4_address: 192.168.50.70
    volumes:
      - data:/data
    container_name: ut3server
    labels:
      - homepage.group=Games
      - homepage.name=Unreal Tournament 3
      - homepage.icon=https://raw.githubusercontent.com/GameServerManagers/LinuxGSM/refs/heads/master/lgsm/data/gameicons/ut3-icon.png
      - homepage.href=steam://connect/192.168.50.70:7777
      #- homepage.widget.type=gamedig
      #- homepage.widget.serverType=unrealtournament3
      #- homepage.widget.url=udp://192.168.50.70:6500
      #- homepage.widget.fields=["status", "map", "currentPlayers", "ping"]
      - homepage.container=ut3server
      - homepage.showStats=false
volumes:
  data:
    name: ut3server_data
networks:
  llamamac:
    name: llamamac
    driver: macvlan
    driver_opts:
      parent: enp6s18
    ipam:
      config:
        - subnet: "192.168.50.0/23"
          gateway: "192.168.50.1"