[[stack]]
name = "unreal_tournament_3"
tags = ["ice", "games"]
[stack.config]
server = "darkmatter"
linked_repo = "game_servers"
webhook_enabled = false
run_directory = "games/ut3server"
config_files = [
  { path = "common.cfg", requires = "None" },
  { path = "UTGame.ini", requires = "None" },
  { path = "UTWeb.ini", requires = "None" }
]
post_deploy.command = """
docker cp UTGame.ini ut3server:/data/serverfiles/UTGame/Config/ut3server/
docker exec ut3server chown 1000:1000 /data/serverfiles/UTGame/Config/ut3server/UTGame.ini
docker cp UTWeb.ini ut3server:/data/serverfiles/UTGame/Config/ut3server/
docker exec ut3server chown 1000:1000 /data/serverfiles/UTGame/Config/ut3server/UTWeb.ini
docker cp common.cfg ut3server:/data/config-lgsm/ut3server/
docker exec ut3server chown 1000:1000 /data/config-lgsm/ut3server/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=ut3
####container name
CT_NAME=ut3server
####gamedig game type
GD_TYPE_ID=unrealtournament3
####server game port
GAME_PORT=7777
####server query port
GAME_QUERY=6500
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""