services:
  newt:
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT=https://pangolin.at.lanallnight.com
      - NEWT_ID=3s1akgx094hv6ug
      - NEWT_SECRET=g98s365ugh0yjvoyzgso0mxa1ufcaxcqdj7fempvfzx0y7sr
      - DOCKER_SOCKET=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - llamanet
networks:
  llamanet:
    driver: bridge
    name: llamanet