[[stack]]
name = "satisfactory"
tags = ["ice", "games"]
[stack.config]
server = "darkmatter"
linked_repo = "game_servers"
webhook_enabled = false
run_directory = "games/sfserver"
config_files = [
  { path = "common.cfg", requires = "None" }
]
post_deploy.command = """
docker cp common.cfg sfserver:/data/config-lgsm/sfserver/
docker exec sfserver chown 1000:1000 /data/config-lgsm/sfserver/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=sf
####container name
CT_NAME=sfserver
####gamedig game type
GD_TYPE_ID=satisfactory
####server game port
GAME_PORT=7777
####server query port
GAME_QUERY=157777
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""