[[stack]]
name = "satisfactory"
tags = ["gs2", "games"]
[stack.config]
server = "gameserver2"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/sfserver"
post_deploy.command = """
docker cp common.cfg sfserver:/data/config-lgsm/sfserver/
docker exec sfserver chown 1000:1000 /data/config-lgsm/sfserver/common.cfg
"""