[[stack]]
name = "squad"
tags = ["ice", "games"]
[stack.config]
server = "darkamtter"
linked_repo = "docker"
webhook_enabled = false
run_directory = "games/squadserver"
config_files = [
  { path = "common.cfg", requires = "None" }
  { path = "Game.ini", requires = "None" }
]
post_deploy.command = """
docker cp squadserver.cfg squadserver:/data/serverfiles/SquadGame/ServerConfig
docker exec squadserver chown 1000:1000 /data/serverfiles/SquadGame/ServerConfig/squadserver.cfg
docker cp common.cfg squadserver:/data/config-lgsm/squadserver/
docker exec squadserver chown 1000:1000 /data/config-lgsm/squadserver/common.cfg
"""
environment = """
####lgsm short name
LGSM_SHORT=squad
####container name
CT_NAME=squadserver
####gamedig game type
GD_TYPE_ID=squad
####server game port
GAME_PORT=7787
####server query port
GAME_QUERY=27165
####server ip
GAME_IP=10.42.0.XX
####macvlan host subnet
IF_SUBNET=10.42.0.0/24
####macvlan host gateway
IF_GATEWAY=10.42.0.1
####macvlan host interface
IF_NAME=br0
"""